// SPDX-License-Identifier: Apache-2.0
package dev.scex.si;
import dev.scex.si.reactor.ReactorCycle;
import dev.scex.si.reactor.ReactorCycle.Part;
import dev.scex.si.reactor.ReactorCycle.Profile;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

/** Golden data is frozen normal game NBT; expected states are not generated by this model. */
public final class ReactorReferenceContract {
    private ReactorReferenceContract(){}
    private static final Map<String,Profile> PROFILES=new LinkedHashMap<>();
    static {
        for(int cells:new int[]{1,2,4}){PROFILES.put("U"+cells,Profile.fuel(cells,false));PROFILES.put("M"+cells,Profile.fuel(cells,true));}
        for(int size:new int[]{10,30,60})PROFILES.put("C"+size,Profile.cell(size*1000));
        PROFILES.put("RSH",Profile.condensator(20000));PROFILES.put("LZH",Profile.condensator(100000));
        PROFILES.put("V",Profile.vent(1000,6,0));PROFILES.put("VR",Profile.vent(1000,5,5));
        PROFILES.put("VO",Profile.vent(1000,20,36));PROFILES.put("VA",Profile.vent(1000,12,0));
        PROFILES.put("VC",Profile.componentVent());
        PROFILES.put("X",Profile.exchanger(2500,12,4));PROFILES.put("XR",Profile.exchanger(5000,0,72));
        PROFILES.put("XC",Profile.exchanger(5000,36,0));PROFILES.put("XA",Profile.exchanger(10000,24,8));
        PROFILES.put("R",Profile.reflector(30000));PROFILES.put("RT",Profile.reflector(120000));PROFILES.put("RI",Profile.reflector(0));
        PROFILES.put("P",Profile.plating(1000));PROFILES.put("PH",Profile.plating(2000));PROFILES.put("PC",Profile.plating(500));
    }
    private static Part[] parse(String text){Part[] p=new Part[54];if(text.isEmpty())return p;
        for(String entry:text.split(";")){String[] e=entry.split(",");p[Integer.parseInt(e[0])]=new Part(PROFILES.get(e[1]),Integer.parseInt(e[2]),Integer.parseInt(e[3]));}return p;}
    private static String encode(Part[] p){StringBuilder s=new StringBuilder();for(int i=0;i<p.length;i++)if(p[i]!=null){
        if(!s.isEmpty())s.append(';');String key="?";for(var e:PROFILES.entrySet())if(e.getValue().equals(p[i].profile())){key=e.getKey();break;}
        s.append(i).append(',').append(key).append(',').append(p[i].stored()).append(',').append(p[i].remaining());}return s.toString();}
    public static void main(String[] args)throws Exception{
        Part[] parts=new Part[54];long heat=0;double energy=0;String label="";int checks=0,cases=0,failures=0;
        for(String line:Files.readAllLines(Path.of(args[0]))){String[] s=line.split("\t",-1);
            switch(s[0]){
                case "CASE" -> {label=s[1];heat=Long.parseLong(s[2]);parts=parse(s[3]);energy=0;cases++;}
                case "STEP" -> {
                    ReactorCycle.Result result=ReactorCycle.step(parts,3,heat,Boolean.parseBoolean(s[2]));
                    heat=result.hullHeat();parts=result.parts();energy+=20*result.euPerTick();
                    String actual=encode(parts);boolean pass=heat==Long.parseLong(s[3])&&(int)(result.euPerTick()/5)==Integer.parseInt(s[4])&&actual.equals(s[5]);checks+=3;
                    if(!pass){if(failures<20)System.out.println("MISMATCH "+label+" tick="+s[1]+" heat="+heat+"/"+s[3]+" eu="+result.euPerTick()+" output="+s[4]+" actual="+actual+" expected="+s[5]);failures++;}
                }
                case "ENERGY" -> {checks++;if(energy!=Double.parseDouble(s[1])){if(failures<20)System.out.println("ENERGY "+label+" actual="+energy+" expected="+s[1]);failures++;}}
                default -> { }
            }
        }
        System.out.println("SCEX_REACTOR_REFERENCE cases="+cases+" checks="+checks+" failures="+failures);
        if(failures>0)throw new AssertionError("Reference mismatches: "+failures);
    }
}
